### ISSUE TITLE
[Refactor] stock_service 분리로 인한 코드 수정

### ISSUE THREAD

**Issue by nayoonk928** [Reservation-Purchase-System/purchase-service#4]
### Description
* stock_service 분리로 인한 코드 수정

### TODO
- [x] StockClient 구현
- [x] stock_service에 제공할 initial controller 구현
- [x] 재고수량 요청 로직 수정 (product_service에 요청 -> stock_service에 요청)
- [x] 테스트 코드 수정
- [x] 로깅 테이블 추가
